### ISSUE TITLE
Seeking Clarification on WASM Usage and Bundle Size in Cloudflare Pages Deployment

### ISSUE THREAD

**Issue by erados** [harlan-zw/nuxt-og-image-playground#2]
### Details

Hi, I have a couple of questions regarding your Cloudflare Pages deployment:

1. It seems that Cloudflare Pages does not support WASM[^1], but when I clone and build your repo, the configuration yields a WASM file. Could you clarify how this works in your deployment?

2. The total bundle size after build is “5.26 MB (1.99 MB gzip),” which exceeds the free tier limit for Cloudflare Pages Workers. How did you manage the deployment despite this?

Thanks for your help!

![image](https://github.com/user-attachments/assets/cddd4487-2111-4aac-8ae3-fffc7ee52ea4)

[^1]: https://nuxtseo.com/og-image/guides/compatibility#vercel-edge-netlify-edge-cloudflare-pages

**Comment by erados** [comment]
I'm working on a side project ([Rulebook](https://rulebook.the-babel.com/votes/71)) that includes dynamic routes, and I'm trying to generate dynamic OG images for them. I came across your `nuxt-og-image-playground` repo and was curious about how you managed to deploy it to Cloudflare Pages.

Since I need to support non-English characters, I may need to add custom fonts, which might push me toward a paid plan. I’m exploring different options and would appreciate any insights. Thanks!

**Comment by harlan-zw** [comment]
1. Cloudflare does support WASM, I've updated the compatibility guide to make that clearer. 
2. Yes, the dependencies needed to generate a runtime OG Image are huge. Unfortunately, there is not a workaround for this if you need runtime images. I'd recommend just upgrading to the $5 /mo plan.
